application: helloworld
version: 1
runtime: python
api_version: 1

handlers:

- url: /javascripts
  static_dir: javascripts
  
- url: .*/index\.html
  script: index.py

- url: /create_sy
  script: index.py
  
- url: /manage_sy
  script: index.py 

- url: /vote_sy.*
  script: index.py

- url: /results.*
  script: index.py

- url: /view_all
  script: index.py